# Generated by Django 6.1 on 2026-08-31 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receivables', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inventory', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_current_assets', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('accounts_payable', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('short_term_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_current_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_positions', to='businesses.business')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='businesses.business')),
            ],
        ),
    ]
